version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - express
      - nextjs

  express:
    build:
      context: ./express
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production

  nextjs:
    build:
      context: ./nextjs
      dockerfile: Dockerfile
    command: sh -c "npm i && npm run dev"
    volumes:
      - ./nextjs:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - express
